import {
  CreditCard,
  Inbox,
  Handshake,
  Receipt,
  ShieldCheck,
  BookOpen,
  TrendingUp,
  Route,
  Package,
  Eye,
  Lock,
  Building2,
  GitMerge,
  FileText,
  type LucideIcon,
} from "lucide-react";

export const iconMap: Record<string, LucideIcon> = {
  card: CreditCard,
  inbox: Inbox,
  handshake: Handshake,
  receipt: Receipt,
  "shield-check": ShieldCheck,
  book: BookOpen,
  "trending-up": TrendingUp,
  route: Route,
  package: Package,
  eye: Eye,
  lock: Lock,
  building: Building2,
  "git-merge": GitMerge,
  "file-text": FileText,
  "credit-card": CreditCard,
};
